# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 106997de794c9f8f2e7fe96f587c0406fa725fee7d7d9735149d5719caa5520ff0f5995917ad921b6a637481a8004a5c1d4a4663dd5c58e083f081936bf4e81f

test:
  secret_key_base: 503884ed72cfda279b2c5307ac2b062c5a3f0e88f0ea70c839584fcdf49ea05d03a0fa036fc07f1a8c5731ffdcfeaea6ffe7f988386d0bc051f8997e2a1040f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
